### ISSUE TITLE
examples/bar.go:83:6: unknown field 'Lang' in struct literal of type opts.ToolBoxFeatureDataView

### ISSUE THREAD

**Issue by juanpabloaj** [go-echarts/examples#24]
when I tried to run the examples I got that message 

    examples/bar.go:83:6: unknown field 'Lang' in struct literal of type opts.ToolBoxFeatureDataView

I tried it in go 1.15.3

```
$ go version
go version go1.15.3 darwin/amd64
```

**Comment by chenjiandongx** [comment]
@juanpabloaj I have upgrade go-ecahrts dependency version to v2.0.1, it should work now.
