### ISSUE TITLE
SunBurst and Tree examples make `go run` fail

### ISSUE THREAD

**Issue by mperrien** [go-echarts/examples#28]
```
❯ go run .
# github.com/go-echarts/go-echarts-examples/examples
examples/sunburst.go:14:32: undefined: opts.SunBurstData
examples/sunburst.go:15:18: undefined: opts.SunBurstData
examples/sunburst.go:17:25: undefined: opts.SunBurstData
examples/sunburst.go:31:22: undefined: charts.Sunburst
examples/sunburst.go:32:14: undefined: charts.NewSunburst
examples/tree.go:12:20: undefined: opts.TreeData
examples/tree.go:52:14: undefined: opts.TreeData
examples/tree.go:59:18: undefined: charts.Tree
examples/tree.go:60:11: undefined: charts.NewTree
examples/tree.go:68:4: undefined: charts.WithTreeOpts
examples/tree.go:68:4: too many errors
```

Removing the `examples/sunburst.go` and `examples/tree.go` files makes for a quick fix and allows the server to run.

**Comment by chenjiandongx** [comment]
@mperrien Hi

go-echarts master branch is under developing, hench it may add some new features on it sometimes.

You could use the `replace` keyword to handle that problem, code shown below.

```
# gomod
module github.com/go-echarts/go-echarts-examples

go 1.15

require github.com/go-echarts/go-echarts/v2 v2.2.3

// dev mode
replace (
	github.com/go-echarts/go-echarts/v2 => ../go-echarts
)
```

And then pull the latest master branch code from github
```shell
> cd $go-echarts-project-path
> git pull origin master
```

**Comment by ozzyst** [comment]
`git checkout fe3950f3b56146c88986817a231b1c4da54e2245`

The problem in the last commit. You can revert it or checkout to the previous.

**Comment by chenjiandongx** [comment]
@mperrien @ozzyst 

go-echarts  v2.2.4 has been released and this example repo has used to the latest version now.

**Comment by mperrien** [comment]
@mperrien @ozzyst

It works now, thanks to both of you for the quick response!
