### ISSUE TITLE
line 图没有显示 label

### ISSUE THREAD

**Issue by yinchunxiang** [go-echarts/examples#32]
用 example 里面的代码跑的，但是 line 图并没有显示 label
<img width="1224" alt="image" src="https://user-images.githubusercontent.com/1582781/227513510-a90a1a53-fa6f-49f4-96d9-5d64541dfb66.png">

**Comment by yinchunxiang** [comment]
@Koooooo-7 辛苦帮看下

**Comment by Koooooo-7** [comment]
Hi @yinchunxiang , sorry for the delay.  the `example repo` is outdate to sync the fix in go-echarts [#268](https://github.com/go-echarts/go-echarts/pull/268).
I update it on #33  now, after merge, it gonna works.

**Comment by Koooooo-7** [comment]
Fixed.
